spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka
  instance:
    #lease-renewal-interval-in-seconds: 2 
    #lease-expiration-duration-in-seconds: 5 
    instance-id: dept-8001.com  
    prefer-ip-address: true       

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.mldn.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
spring:
  profiles: dev
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: '{cipher}AQBW5yyn0xwU5ho0OZnMDQ/z7n8K8U2gNrjPivHdBV/Ki+QC+DzlB0mn6zDR1Raz+sfpcNrL2VzWtNPb1ts4ioqP4LmmPKM5sf+ZIUKHmNoslrSM4o6HvdhyFmoxRAsIiOXfiUxbB9FeICsIyxrcz2Go1JwElYfTX12yn5j1pZlvACl4nUDuMGTNMVvslzDhYouv0Dr3W5FXB8fZz72hUvFLAlEUucSyc+sGjcCFVLhIrGsH6rMK9/oFpx0VR4DVUF1RLnQhGuGrKGHUWvf+Z84tdylEQ8W8yGkHrVA8cIIR8idLjadrBqQ+/BpEbh4wvawtRdL2DrRLwJRP+KbICcU1iXUOBQeyB0n1Utd5ARHm6qjWnmwQSHgw2xIvMWtojlU='
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client 
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka
  instance:
    #lease-renewal-interval-in-seconds: 2 
    #lease-expiration-duration-in-seconds: 5 
    instance-id: dept-8001.com   
    prefer-ip-address: true       

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.mldn.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
spring:
  profiles: beta
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: '{cipher}AQBW5yyn0xwU5ho0OZnMDQ/z7n8K8U2gNrjPivHdBV/Ki+QC+DzlB0mn6zDR1Raz+sfpcNrL2VzWtNPb1ts4ioqP4LmmPKM5sf+ZIUKHmNoslrSM4o6HvdhyFmoxRAsIiOXfiUxbB9FeICsIyxrcz2Go1JwElYfTX12yn5j1pZlvACl4nUDuMGTNMVvslzDhYouv0Dr3W5FXB8fZz72hUvFLAlEUucSyc+sGjcCFVLhIrGsH6rMK9/oFpx0VR4DVUF1RLnQhGuGrKGHUWvf+Z84tdylEQ8W8yGkHrVA8cIIR8idLjadrBqQ+/BpEbh4wvawtRdL2DrRLwJRP+KbICcU1iXUOBQeyB0n1Utd5ARHm6qjWnmwQSHgw2xIvMWtojlU='
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client 
    