spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
spring:
  profiles: beta
  application:
    name: microcloud-config-client 
info:
  app.name: mldn-microcloud-dev-1
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  app.version: v-dev-1.0.0
---
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
spring:
  profiles: dev
  application:
    name: microcloud-config-client
info:
  app.name: mldn-microcloud-beta-1
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  app.version: v-beta-1.0.0
    