spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
spring:
  profiles: beta
  application:
    name: microcloud-config-client 
---
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7301/eureka
spring:
  profiles: dev
  application:
    name: microcloud-config-client
      
    