spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microcloud-config-eureka-client
server:
  port: 7001
eureka:  
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka
    register-with-eureka: false 
    fetch-registry: false
  instance:
    hostname: eureka-7001.com
security:
  basic:
    enabled: true
  user:
    name: edmindev
    password: mldnjava


---
spring:
  profiles: beta
  application:
    name: microcloud-config-eureka-client 
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka
  instance:
    #lease-renewal-interval-in-seconds: 2 
    #lease-expiration-duration-in-seconds: 5
    instance-id: eureka-7001.com   
    prefer-ip-address: true      
security:
  basic:
    enabled: true
  user:
    name: edminbeta
    password: mldnjava

      
    