spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microcloud-config-eureka-client # 实例所在主机名称
server:
  port: 7001

---
spring:
  profiles: beta
  application:
    name: microcloud-config-eureka-client # 实例所在主机名称
server:
  port: 7002

    